<?
$arNewUrlRewrite=array(
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."activity/gosserv/for/([0-9]+)/(.+?)/([0-9]+)/([0-9]+)/(.+?)/#",
		"RULE"	=>	"FOR=$1&MODE=$2&SECTION_ID=$3&ELEMENT_ID=$4&PROPERTY=$5&",
		"ID"	=>	"",
		"PATH"	=>	"".WIZARD_SITE_DIR."activity/gosserv/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."activity/gosserv/for/([0-9]+)/(.+?)/([0-9]+)/([0-9]+)/#",
		"RULE"	=>	"FOR=$1&MODE=$2&SECTION_ID=$3&ELEMENT_ID=$4&PROPERTY=MAIN_INFO&",
		"ID"	=>	"",
		"PATH"	=>	"".WIZARD_SITE_DIR."activity/gosserv/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."about/videogallery/([0-9]+)/#",
		"RULE"	=>	"ELEMENT_ID=$1&",
		"ID"	=>	"",
		"PATH"	=>	"".WIZARD_SITE_DIR."city/videogallery/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."activity/gosserv/for/([0-9]+)/(.+?)/#",
		"RULE"	=>	"FOR=$1&MODE=$2&SECTION_ID=0",
		"ID"	=>	"",
		"PATH"	=>	"".WIZARD_SITE_DIR."activity/gosserv/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."about/statistics/benefits/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"".WIZARD_SITE_DIR."about/statistics/benefits/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."about/mun-order/selected/#",
		"RULE"	=>	"selected=Y&",
		"ID"	=>	"",
		"PATH"	=>	"".WIZARD_SITE_DIR."about/mun-order/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."about/officials/blogs/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:blog",
		"PATH"	=>	"".WIZARD_SITE_DIR."about/officials/blogs/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."about/officials/texts/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"".WIZARD_SITE_DIR."about/officials/texts/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."activity/gosserv/for/([0-9]+)/#",
		"RULE"	=>	"FOR=$1&MODE=category",
		"ID"	=>	"",
		"PATH"	=>	"".WIZARD_SITE_DIR."activity/gosserv/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."about/stateservice/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"".WIZARD_SITE_DIR."about/stateservice/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."about/photogallery/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:photogallery",
		"PATH"	=>	"".WIZARD_SITE_DIR."about/photogallery/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."info/photogallery/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:photogallery",
		"PATH"	=>	"".WIZARD_SITE_DIR."info/photogallery/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."about/inspections/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"".WIZARD_SITE_DIR."about/inspections/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."exhibition/itogi/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"".WIZARD_SITE_DIR."exhibition/itogi/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."about/regulatory/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"".WIZARD_SITE_DIR."about/regulatory/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."about/vacancies/job/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"".WIZARD_SITE_DIR."about/vacancies/job/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."about/officials/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"".WIZARD_SITE_DIR."about/officials/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."officials/texts/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"".WIZARD_SITE_DIR."officials/texts/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."officials/blogs/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:blog",
		"PATH"	=>	"".WIZARD_SITE_DIR."officials/blogs/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."about/mun-order/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"".WIZARD_SITE_DIR."about/mun-order/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."about/massmedia/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"".WIZARD_SITE_DIR."about/massmedia/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."vacancies/list/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"".WIZARD_SITE_DIR."vacancies/list/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."administration/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"".WIZARD_SITE_DIR."administration/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."info/massmedia/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"".WIZARD_SITE_DIR."info/massmedia/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."feedback/faq/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:support.faq",
		"PATH"	=>	"".WIZARD_SITE_DIR."feedback/faq/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."vacancies/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"".WIZARD_SITE_DIR."vacancies/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."officials/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"".WIZARD_SITE_DIR."officials/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."info/news/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"".WIZARD_SITE_DIR."info/news/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."documents/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"".WIZARD_SITE_DIR."documents/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."info/anounces/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"".WIZARD_SITE_DIR."/infoanounces/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."messages/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"".WIZARD_SITE_DIR."messages/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."projects/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"".WIZARD_SITE_DIR."projects/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."activity/gosserv/#",
		"RULE"	=>	"FOR=0&MODE=category&SECTION_ID=0",
		"ID"	=>	"",
		"PATH"	=>	"".WIZARD_SITE_DIR."activity/gosserv/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."events/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"".WIZARD_SITE_DIR."events/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."news/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"".WIZARD_SITE_DIR."news/index.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."about/rukovodstvo/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:socialnetwork_user",
		"PATH"	=>	"".WIZARD_SITE_DIR."about/rukovodstvo/user.php",
	),
	array(
		"CONDITION"	=>	"#^".WIZARD_SITE_DIR."about/visits/#",
		"RULE"	=>	"",
		"ID"	=>	"bitrix:news",
		"PATH"	=>	"".WIZARD_SITE_DIR."about/visits/index.php",
	),
);
 ?>