<?
$aMenuLinks = Array(
    Array(
        "ВКонтакте",
        "#vk",
        Array(),
        Array("CLASS"=>"vk"),
        ""
    ),
    Array(
        "Twitter",
        "#tw",
        Array(),
        Array("CLASS"=>"tw"),
        ""
    ),
    Array(
        "Facebook",
        "#fb",
        Array(),
        Array("CLASS"=>"fb"),
        ""
    ),
    Array(
        "Instagramm",
        "#inst",
        Array(),
        Array("CLASS"=>"inst"),
        ""
    ),
    Array(
        "LinkedIn",
        "#in",
        Array(),
        Array("CLASS"=>"in"),
        ""
    ),
    Array(
        "GooglePlus",
        "#gplus",
        Array(),
        Array("CLASS"=>"gplus"),
        ""
    )
);
?>