<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Форум программы «Доступное и комфортное жилье - гражданам России»");$APPLICATION->SetPageProperty("show_timestamp_x", "N");
?><?$APPLICATION->IncludeComponent(
	"bitrix:forum",
	"",
	Array(
		"THEME" => "gray",
		"SHOW_TAGS" => "Y",
		"SHOW_AUTH_FORM" => "Y",
		"SHOW_NAVIGATION" => "Y",
		"SHOW_SUBSCRIBE_LINK" => "N",
		"SHOW_LEGEND" => "Y",
		"SHOW_STATISTIC" => "Y",
		"SHOW_NAME_LINK" => "Y",
		"SHOW_FORUMS" => "Y",
		"SHOW_FIRST_POST" => "N",
		"SHOW_AUTHOR_COLUMN" => "N",
		"TMPLT_SHOW_ADDITIONAL_MARKER" => "",
		"SMILES_COUNT" => "100",
		"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
		"PATH_TO_ICON" => "/bitrix/images/forum/icon/",
		"PAGE_NAVIGATION_TEMPLATE" => "forum",
		"PAGE_NAVIGATION_WINDOW" => "5",
		"WORD_WRAP_CUT" => "23",
		"WORD_LENGTH" => "50",
		"SEO_USER" => "N",
		"USE_LIGHT_VIEW" => "Y",
		"SEF_MODE" => "N",
		"CHECK_CORRECT_PATH_TEMPLATES" => "Y",
		"FID" => Array(),
		"USER_PROPERTY" => array(),
		"FILES_COUNT" => "5",
		"FORUMS_PER_PAGE" => "10",
		"TOPICS_PER_PAGE" => "10",
		"MESSAGES_PER_PAGE" => "10",
		"TIME_INTERVAL_FOR_USER_STAT" => "10",
		"DATE_FORMAT" => "d.m.Y",
		"DATE_TIME_FORMAT" => "d.m.Y H:i:s",
		"IMAGE_SIZE" => "500",
		"SEND_MAIL" => "E",
		"SEND_ICQ" => "A",
		"SET_NAVIGATION" => "Y",
		"SET_TITLE" => "Y",
		"SET_PAGE_PROPERTY" => "Y",
		"DISPLAY_PANEL" => "N",
		"USE_RSS" => "N",
		"SHOW_FORUM_ANOTHER_SITE" => "Y",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600",
		"CACHE_TIME_USER_STAT" => "60",
		"SHOW_VOTE" => "N",
		"VARIABLE_ALIASES" => Array(
			"FID" => "FID",
			"TID" => "TID",
			"MID" => "MID",
			"UID" => "UID"
		)
	),
false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>