<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Title");$APPLICATION->SetPageProperty("show_timestamp_x", "N");
?><a style="float:right;position:relative;z-index:1;" href="#SITE_DIR#info/photogallery/rss.php" title="RSS"><img width="14px" height="14px" alt="rss" src="#SITE_DIR#images/icon_rss.png"/></a>
<?$APPLICATION->IncludeComponent("bitrix:photogallery", ".default", array(
	"USE_LIGHT_VIEW" => "Y",
	"IBLOCK_TYPE" => "photovideogallery",
	"IBLOCK_ID" => "#PHOTOGALLERY_IBLOCK_ID#",
	"PATH_TO_USER" => "",
	"DRAG_SORT" => "Y",
	"USE_COMMENTS" => "N",
	"SEF_MODE" => "Y",
	"SEF_FOLDER" => "#SITE_DIR#info/photogallery/",
	"CACHE_TYPE" => "A",
	"CACHE_TIME" => "3600",
	"SET_TITLE" => "Y",
	"ALBUM_PHOTO_SIZE" => "120",
	"THUMBNAIL_SIZE" => "100",
	"ORIGINAL_SIZE" => "1280",
	"PHOTO_LIST_MODE" => "Y",
	"SHOWN_ITEMS_COUNT" => "6",
	"USE_RATING" => "N",
	"SHOW_TAGS" => "N",
	"UPLOADER_TYPE" => "applet",
	"APPLET_LAYOUT" => "extended",
	"UPLOAD_MAX_FILE_SIZE" => "2",
	"USE_WATERMARK" => "Y",
	"WATERMARK_RULES" => "USER",
	"PATH_TO_FONT" => "",
	"WATERMARK_MIN_PICTURE_SIZE" => "800",
	"SHOW_LINK_ON_MAIN_PAGE" => array(
		0 => "id",
		1 => "shows",
		2 => "rating",
		3 => "comments",
	),
	"SECTION_SORT_BY" => "UF_DATE",
	"SECTION_SORT_ORD" => "DESC",
	"ELEMENT_SORT_FIELD" => "sort",
	"ELEMENT_SORT_ORDER" => "desc",
	"DATE_TIME_FORMAT_DETAIL" => "d.m.Y",
	"DATE_TIME_FORMAT_SECTION" => "d.m.Y",
	"SECTION_PAGE_ELEMENTS" => "15",
	"ELEMENTS_PAGE_ELEMENTS" => "50",
	"PAGE_NAVIGATION_TEMPLATE" => "",
	"JPEG_QUALITY1" => "100",
	"JPEG_QUALITY" => "100",
	"ADDITIONAL_SIGHTS" => array(
	),
	"SHOW_NAVIGATION" => "N",
	"SEF_URL_TEMPLATES" => array(
		"index" => "index.php",
		"section" => "#SECTION_ID#/",
		"section_edit" => "#SECTION_ID#/action/#ACTION#/",
		"section_edit_icon" => "#SECTION_ID#/icon/action/#ACTION#/",
		"upload" => "#SECTION_ID#/action/upload/",
		"detail" => "#SECTION_ID#/#ELEMENT_ID#/",
		"detail_edit" => "#SECTION_ID#/#ELEMENT_ID#/action/#ACTION#/",
		"detail_list" => "#SECTION_ID#/#ELEMENT_ID#/list/",
		"search" => "search/",
	)
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>